@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/application/home

### Cria um Recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "assunto": "Olá, mundo 6!",
    "mensagem": "Bem-vindo ao meu aplicativo de recados 6!",
    "de": "M64ia",
    "para": "Jeferson"
}

### Lista Recados

# @name RecadosControllerAll
GET {{baseUrl}}/recados/all?limit=10

### Lista um recado
# @name RecadosControllerOne

GET {{baseUrl}}/recados/3

### Atualiza um recado

PATCH {{baseUrl}}/recados/update/2
Content-Type: application/json

{
  "assunto": "Olá Jeferson",
  "bla bla bla":123
}

### Apaga um recado

DELETE {{baseUrl}}/recados/delete/3

