version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=starter
    volumes:
      - starter_pg_data:/bitnami/postgresql

volumes:
  starter_pg_data:

